"""
YamlExporter — writes ScoredElement lists to locators.yaml files.

Output format is fully compatible with LocatorRepository.from_yaml() and
LocatorRepository.from_directory(), so generated files drop straight into
the screens/<name>/locators.yaml slot in the standard project layout.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from desktop_automation_platform.scanner.locator_generator import ScoredElement
from desktop_automation_platform.utils.logger import get_logger

_log = get_logger(__name__)

_HEADER = """\
# Auto-generated by Desktop Automation Platform — Locator Scanner
# Review and rename keys before committing.
# Strategy priority: automation_id > name > class_name > control_type
#
"""


class YamlExporter:
    """Serialises ScoredElement records to a style-guide-compliant locators.yaml."""

    def export(
        self,
        scored: list[ScoredElement],
        output_path: str | Path,
        overwrite: bool = False,
        add_metadata: bool = True,
    ) -> str:
        """
        Write ``scored`` elements to ``output_path`` as a YAML locator repository.

        Parameters
        ----------
        scored:
            Output of ``LocatorGenerator.generate()``.
        output_path:
            Destination file path. Parent directories are created automatically.
        overwrite:
            Allow overwriting an existing file.
        add_metadata:
            Include ``metadata:`` block with control_type, bounding_rect,
            and supported_patterns. Useful for review; can be stripped later.

        Returns
        -------
        str
            Absolute path of the written file.
        """
        path = Path(output_path).resolve()
        if path.exists() and not overwrite:
            raise FileExistsError(
                f"Output already exists: {path}. Pass overwrite=True to replace it."
            )
        path.parent.mkdir(parents=True, exist_ok=True)

        repo: dict[str, Any] = {}
        for s in scored:
            repo[s.key] = self._to_entry(s, add_metadata=add_metadata)

        yaml_text = yaml.dump(
            repo,
            sort_keys=True,
            allow_unicode=True,
            default_flow_style=False,
            indent=2,
        )
        path.write_text(_HEADER + yaml_text, encoding="utf-8")

        _log.info("yaml_exported", path=str(path), element_count=len(repo))
        return str(path)

    def export_summary(self, scored: list[ScoredElement]) -> str:
        """Return a human-readable summary string (for Robot Framework log output)."""
        lines = [f"Locator scan complete — {len(scored)} elements found\n"]
        for s in scored:
            score_tag = (
                "★★★" if s.score >= 100
                else "★★ " if s.score >= 70
                else "★  "
            )
            name_hint = s.element.name or s.element.automation_id or s.element.class_name or "?"
            lines.append(
                f"  {score_tag} [{s.primary_strategy:>14}]  {s.key:<40}  ({name_hint})"
            )
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Serialisation helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _to_entry(s: ScoredElement, add_metadata: bool) -> dict[str, Any]:
        entry: dict[str, Any] = {
            "primary": {
                "strategy": s.primary_strategy,
                "value": s.primary_value,
            }
        }

        if s.fallbacks:
            entry["fallback"] = [
                {"strategy": fb["strategy"], "value": fb["value"]}
                for fb in s.fallbacks
            ]

        if add_metadata:
            meta: dict[str, Any] = {}
            elem = s.element
            if elem.control_type:
                meta["control_type"] = elem.control_type
            if elem.bounding_rect:
                meta["bounding_rect"] = elem.bounding_rect
            if elem.supported_patterns:
                meta["supported_patterns"] = elem.supported_patterns
            if elem.name and s.primary_strategy != "name":
                meta["name"] = elem.name
            if meta:
                meta["description"] = (
                    f"Auto-generated — review and update this description. "
                    f"Score: {s.score}/100."
                )
                entry["metadata"] = meta

        return entry
